### ISSUE TITLE
Regarding change of masks in MixColumns

### ISSUE THREAD

**Issue by sayma10** [quentin-meunier/LeakageVerif#3]
Hello Sir,

Could you please help me why mix Columns operations changes mask from M1, M2, M3 and M4 to M1', M2', M3' and M4'

def mix_columns(x):
    def xtime(y):
        return (y << 1) ^ ((y >> 7) & constant(0x1b, 8))

    for i in range(4):
        t        = x[0][i]
        tmp      = x[0][i] ^ x[1][i] ^ x[2][i] ^ x[3][i]
        tm       = x[0][i] ^ x[1][i]
        tm       = xtime(tm)
        x[0][i] ^= tm ^ tmp
        tm       = x[1][i] ^ x[2][i]
        tm       = xtime(tm)
        x[1][i] ^= tm ^ tmp
        tm       = x[2][i] ^ x[3][i]
        tm       = xtime(tm)
        x[2][i] ^= tm ^ tmp
        tm       = x[3][i] ^ t
        tm       = xtime(tm)
        x[3][i] ^= tm ^ tmp

BR
sayma

**Comment by quentin-meunier** [comment]
Hi,
I answered in your issue from last week, and thus I am closing this one.
